language: sh
dist: xenial  # required for the SSL library needed to download pip for Python 3.7

matrix:
  os:
    - linux
    - windows
  env:
    - TOX_ENV=docs
    - TOX_ENV=flake8
    - TOX_ENV=py27
    - TOX_ENV=py34
    - TOX_ENV=py35
    - TOX_ENV=py36
    - TOX_ENV=py37

allow_failures:
  - os: windows

apt_packages:
  - pandoc

notifications:
  irc:
    channels:
      - "irc.freenode.org#pelican"
    on_success: change

before_install:
  - echo $TRAVIS_OS_NAME
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
        sudo add-apt-repository ppa:deadsnakes/ppa -y;
        sudo apt-get update -qq;
        sudo locale-gen fr_FR.UTF-8 tr_TR.UTF-8;

        if [ "$TOX_ENV" == "py27" ]; then
            sudo apt-get install python2.7;
            export PY_EXE = "python";
        fi
        if [ "$TOX_ENV" == "py34" ]; then
            sudo apt-get install python3.4;
            export PY_EXE = "python3.4";
        fi
        if [ "$TOX_ENV" == "py35" ]; then
            sudo apt-get install python3.5;
            export PY_EXE = "python3.5";
        fi
        if [ "$TOX_ENV" == "py36" ]; then
            sudo apt-get install python3.6;
            export PY_EXE = "python3.6";
        fi
        if [ "$TOX_ENV" == "py37" ]; then
            sudo apt-get install python3.7;
            export PY_EXE = "python3.7";
        fi
    fi
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
        env
    fi
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
        eval "$PY_EXE --version"
    fi
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
        curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py;
        eval "$PY_EXE get-pip.py --user";
        eval "$PY_EXE -m pip install virtualenv --user";
    fi
  - |
    if [ "$TRAVIS_OS_NAME" == "windows" ]; then
        choco install pandoc;
        export PY_EXE="python";

        if [ "$TOX_ENV" == "py27" ]; then
            choco install python --version 2.7.11;
            export PATH="/c/tools/Python:/c/tools/python/Scripts:$PATH";
        fi
        if [ "$TOX_ENV" == "py34" ]; then
            choco install python --version 3.4.4;
            export PATH="/c/Python34:/c/Python34/Scripts:$PATH";
        fi
        if [ "$TOX_ENV" == "py35" ]; then
            choco install python --version 3.5.4;
            export PATH="/c/Python35:/c/Python35/Scripts:$PATH";
        fi
        if [ "$TOX_ENV" == "py36" ]; then
            choco install python --version 3.6.7;
            export PATH="/c/Python36:/c/Python36/Scripts:$PATH";
        fi
        if [ "$TOX_ENV" == "py37" ]; then
            choco install python --version 3.7.1;
            export PATH="/c/Python37:/c/Python37/Scripts:$PATH";
        fi

        $PY_EXE -m pip install virtualenv --user
    fi

  - virutalenv venv
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
        source venv/bin/activate;
    fi

install:
  - python -m pip install --upgrade pip wheel
  - pip --version
  - pip install tox==2.5.0
  - python -m pip install -r requirements/test.pip
  - python -m pip install nose nose-cov coveralls pygments==2.1.3
  - python -m pip install .

script:
  - tox -e $TOX_ENV

after_script:
  - coveralls
