matrix:
  - os: linux
      language: python
      python:
        - 3.5
          env:
            - TOX_ENV=docs
            - TOX_ENV=flake8
            - TOX_ENV=py27
            - TOX_ENV=py34
            - TOX_ENV=py35
        - 3.6
          env:
            - TOX_ENV=py36
      addons:
        apt_packages:
          - pandoc
      before_install:
        - sudo apt-get update -qq
        - sudo locale-gen fr_FR.UTF-8 tr_TR.UTF-8
      install:
        - pip install tox==2.5.0

  - os: windows
      langauge: sh  # python isn't yet "officially" supported on Windows
      env:
        - TOX_ENV=py27
        - TOX_ENV=py37
      before_install:
        - choco install pandoc
        - pip install tox==2.5.0

  - allow_failures:
    - os: windows

script: tox -e $TOX_ENV

notifications:
  irc:
    channels:
      - "irc.freenode.org#pelican"
    on_success: change
