language: sh
matrix:
  include:
  - os: windows
    env: TOX_ENV=py27
    before_install:
      - choco install pandoc
      - choco install python --version 2.7.11
      - export PATH="/c/tools/Python:/c/tools/python/Scripts:$PATH"
      - python --version
      - python -m pip install --upgrade pip wheel
      - python -m pip install -r requirements/test.pip
      - python -m pip install nose nose-cov coveralls pygments==2.1.3
    install:
      - python -m pip install .
    script:
      - nosetests -sv --with-coverage --cover-package=pelican pelican
      - coveralls

  - os: windows
    env: TOX_ENV=py37
    before_install:
      - choco install pandoc
      - choco install python --version 3.7.1
      - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
      - python --version
      - python -m pip install --upgrade pip wheel
      - python -m pip install -r requirements/test.pip
      - python -m pip install nose nose-cov coveralls pygments==2.1.3
    install:
      - python -m pip install .
    script:
      - nosetests -sv --with-coverage --cover-package=pelican pelican
      - coveralls

  allow_failures:
  - os: windows

script: tox -e $TOX_ENV

notifications:
  irc:
    channels:
      - "irc.freenode.org#pelican"
    on_success: change
